### PR TITLE
RCOCOA-2051 Add Static Queries

### PR DESCRIPTION
**Pull request by jsflax**
Adds support to use Codable types to query an atlas cluster, obviating the need to use the old BSON types we introduced.

### CODE REVIEW

**Comment by dianaafanador3** [comment]
@jsflax Can you please rebase this, so the CI can be executed

**Comment by tgoyne** [comment]
This is not in a reviewable state. It is a giant mess of unfinished things and unrelated changes.

**Comment by jsflax** [comment]
Some field renames and added methods snuck in.

If I remove the `MongoQuery` addition (it was experimental and was chatted about when the project started), what else is missing @tgoyne ?

**Comment by tgoyne** [comment]
There is a whole bunch of commented code, random unrelated changes, and very few of the new public things are documented.

**Pull request closed without merging**
