### PR TITLE
use isSwift in schemaForObjectClass correctly

### LINKED ISSUE #6291: Xcode 11: Crash when ObjectiveC-Class inherits from Swift-Class
## Goals
Have an Objective-C-class `B`, that inherits from an RLMObject-subclass created in Swift `A`. The class `A` should have a String-property `identifier` as the *primaryKey*

## Expected Results
`+[RLMObjectSchema schemaForObjectClass:]` returns a correct Schema

## Actual Results
Exception gets thrown
> 'RLMException', reason: 'Primary key property 'identifier' does not exist on object 'A'

## Steps to Reproduce
1. Create a subclass of RLMObject in Swift where the *primaryKey* is a String
2. Create a subclass of the previous class in Objective-C

## Code Sample
https://github.com/uwemeier-sclable/RealmCrashExample

## Additional Info
* This behavior occurs, because in `+[RLMObjectSchema schemaForObjectClass:]` only the original `objectClass` is checked, whether it is a class created in Swift, but not its possible `superClasses` which leads to `+[RLMObjectSchema propertiesForClass:isSwift:]` executing the wrong code.  
* This issue is somewhat related to #6250 but can not be fixed by the solutions proposed there.

## Version of Realm and Tooling
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103

/Applications/Xcode.app/Contents/Developer
Xcode 11.0
Build version 11A420a

/usr/local/bin/pod
1.8.3
Realm (3.19.0)
Realm (~> 3.19)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

(not in use here)

/usr/bin/git
git version 2.21.0 (Apple Git-122)

### PR DESCRIPTION
**Pull request by uwemeier-sclable**
When class has a superClass other than RLMObjectBase
the isSwift-flag should be computed from the superClass 
rather than using the one from the class.  
Fixes #6291

### CODE REVIEW

**Comment by bmunkholm** [comment]
Thanks @uwemeier-sclable !
We only need a testcase showing what didn't work and now works and an update in the changelog.md file.
Did you sign the CLA (see contributing.md)?

**Comment by uwemeier-sclable** [comment]
> Thanks @uwemeier-sclable !
> We only need a testcase showing what didn't work and now works and an update in the changelog.md file.
> Did you sign the CLA (see contributing.md)?

Hi @bmunkholm 
1. A testcase can be found [here](https://github.com/uwemeier-sclable/RealmCrashExample)
2. What exactly should i write to the changelog.md
3. Yes, I've already the google form

**Comment by uwemeier-sclable** [comment]
Is there any progress on this?

**Comment by jsflax** [comment]
Closing due to inactivity. If you want to re-pick this up, please reopen it and have the CI run again.

**Pull request closed without merging**
