### PR TITLE
RCOCOA-1874: Add support for lexicographical comparison for string queries

### PR DESCRIPTION
**Pull request by dianaafanador3**
Added support for string comparison queries, which allows building string 
   queries with the following operators (`>`, `>=`, `<`, `<=`). 
   ([#8008](https://github.com/realm/realm-swift/issues/8008)).

### CODE REVIEW

**Review by leemaguire — APPROVED** [review]
LGTM

**Comment by tgoyne** [comment]
This is silently ignoring case-insensitive modifiers on comparison operators (e.g. `a >[c] b`).

You appear to have modified the generated test files directly rather than modify the template files.

**Comment by tgoyne** [comment]
I don't think we should support case-insensitive comparisons, but we need to report an error rather than silently doing the wrong thing.

**Comment by dianaafanador3** [comment]
@tgoyne solved comments

**Pull request merged**
